//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningTheEP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanningTheEPEntities : DbContext
    {
        private static PlanningTheEPEntities _context;
        public PlanningTheEPEntities()
            : base("name=PlanningTheEPEntities")
        {
        }
        public static PlanningTheEPEntities GetContext()
        {
            if (_context == null)
                _context = new PlanningTheEPEntities();

            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<FirstPlan> FirstPlan { get; set; }
        public virtual DbSet<FullAndFirst> FullAndFirst { get; set; }
        public virtual DbSet<FullPlan> FullPlan { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectArea> SubjectArea { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
