//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningTheEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirstPlan()
        {
            this.FullAndFirst = new HashSet<FullAndFirst>();
        }
    
        public long Id_FPlan { get; set; }
        public Nullable<long> Id_Subject { get; set; }
        public Nullable<long> Id_SubjectArea { get; set; }
        public long Id_Grade { get; set; }
        public double NumberOfHours { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual SubjectArea SubjectArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullAndFirst> FullAndFirst { get; set; }
    }
}
