//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningTheEP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullAndFirst
    {
        public long Id { get; set; }
        public long Id_Plan { get; set; }
        public long Id_FPlan { get; set; }
    
        public virtual FirstPlan FirstPlan { get; set; }
        public virtual FullPlan FullPlan { get; set; }
    }
}
